[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Demo"
version = "0.1.0"
description = "AgentCore Runtime Application using LangChain/LangGraph"
requires-python = ">=3.12,<3.13"
dependencies = [
    "langgraph>=1.0.2",
    "mcp >= 1.19.0",
    "langchain-mcp-adapters >= 0.2.0",
    "langchain >= 1.0.3",
    "bedrock-agentcore >= 1.8.0",
    "botocore[crt] >= 1.35.0",
    "langchain-aws >= 1.0.0",
    "langchain-groq>=1.1.0",
    "langchain-community>=0.3.0",
    "ipykernel>=7.3.0",
    "streamlit>=1.61.1",
    "ddgs>=9.15.0",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "langchain-openai>=1.5.1",
    "langchain-text-splitters>=1.1.2",
    "pypdf>=6.16.1",
    "langchain-huggingface>=1.2.2",
    "sentence-transformers>=5.7.0",
    "ipywidgets>=8.1.8",
    "faiss-cpu>=1.15.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
